catalog/urls.py
from django.urls import path

from catalog.views import (index,
                           FormatsList,
                           AuthorsList,
                           BooksList,
                           BookDetailView,
                           AuthorDetailView,)

urlpatterns = [
    path("", index, name="index"),
    path(
        "formats/",
        FormatsList.as_view(),
        name="formats_list"
    ),
    path(
        "authors/",
        AuthorsList.as_view(),
        name="authors_list"
    ),
    path(
        "books/",
        BooksList.as_view(),
        name="books_list"
    ),
    path(
        "books/<int:pk>",
        BookDetailView.as_view(),
        name="book_detail"
    ),
    path(
        "authors/<int:pk>",
        AuthorDetailView.as_view(),
        name="author_detail"
    )
]

app_name = "catalog"

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include("catalog.urls", namespace="catalog")),

    path("__debug__/", include("debug_toolbar.urls")),
]

catalog/models.py
from django.db import models


class Format(models.Model):
    # Book format

    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=63)
    last_name = models.CharField(max_length=63)
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class Book(models.Model):
    title = models.CharField(max_length=255)
    format = models.ForeignKey(
        Format,
        on_delete=models.CASCADE,
        related_name="books"
    )

    authors = models.ManyToManyField(
        Author,
        related_name="books"
    )

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return f"{self.title} (format: {self.format.name})"

catalog/views.py
from django.shortcuts import render
from django.views import generic

from catalog.models import Book, Author, Format


def index(request):
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_formats = Format.objects.count()

    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_formats": num_formats
    }

    return render(
        request,
        "catalog/index.html",
        context=context
    )


class FormatsList(generic.ListView):
    model = Format
    template_name = "catalog/formats_list.html"
    context_object_name = "formats"


class AuthorsList(generic.ListView):
    model = Author
    template_name = "catalog/authors_list.html"
    context_object_name = "authors"


class BooksList(generic.ListView):
    model = Book
    template_name = "catalog/books_list.html"
    context_object_name = "books"
    queryset = Book.objects.select_related("format")


class BookDetailView(generic.DetailView):
    model = Book
    template_name = "catalog/book_detail.html"
    context_object_name = "book"
    queryset = Book.objects.select_related("format").prefetch_related("authors")


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = "catalog/author_detail.html"
    context_object_name = "author"
    queryset = Author.objects.prefetch_related("books")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Library</title>
</head>
<body>
  {% include "includes/navigation.html" %}

  {% block content %}
  {% endblock %}
</body>
</html>

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ author.first_name }} {{ author.last_name }}</h1>

  {% if author.pseudonym %}
    <p>
      Pseudonym: {{ author.pseudonym }}
    </p>
  {% endif %}

  <p>Books:</p>
  {% if author.books.all %}
    <ul>
      {% for book in author.books.all %}
        <li>
          <a href="{% url 'catalog:book_detail' pk=book.id %}">{{ book.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/authors_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Authors</h1>

  {% if authors %}
    <ul>
      {% for author in authors %}
        <li>
          <a href="{% url 'catalog:author_detail' pk=author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
          {% if author.pseudonym %}
            ({{ author.pseudonym }})
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ book.title }}</h1>

  <p>
    Format: {{ book.format.name }}
  </p>
  <p>Authors:</p>
  <ul>
    {% for author in book.authors.all %}
      <li>
        <a href="{% url 'catalog:author_detail' pk=author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
        {% if author.pseudonym %}
          (Pseudonym: {{ author.pseudonym }})
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/catalog/books_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Books</h1>

  {% if books %}
    <ul>
      {% for book in books %}
        <li>
          <a href="{% url 'catalog:book_detail' pk=book.id %}">{{ book.title }}</a>
          (format: {{ book.format.name }})
        </li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/formats_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Formats</h1>

  {% if formats %}
    <ul>
      {% for format in formats %}
        <li>{{ format.name }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Library</h1>

  <ul>
    <li>Number books: {{ num_books }}</li>
    <li>Number authors: {{ num_authors }}</li>
    <li>Number formats: {{ num_formats }}</li>
  </ul>
{% endblock %}

templates/includes/navigation.html
<a href="{% url 'catalog:index' %}">Home</a>
<a href="{% url 'catalog:books_list' %}">Books</a>
<a href="{% url 'catalog:formats_list' %}">Formats</a>
<a href="{% url 'catalog:authors_list' %}">Authors</a>

<div style="display: inline-block; margin-left: 30px">
  {% if user.is_authenticated %}
    {{ user.username }}
    <form style="display: inline-block" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit">logout</button>
    </form>
  {% else %}
    <a href="{% url 'login' %}">Login</a>
  {% endif %}
</div>